version: '3.1'

services:

  verzeldb:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: verzel
      MYSQL_USER: master
      MYSQL_PASSWORD: master

  verzelbackend:
    build: ./backend
    restart: always
    depends_on:
      - verzeldb
    ports:
      - 5000:80
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: verzel
      MYSQL_USER: master
      MYSQL_PASSWORD: master

  verzelfrontend:
    build: ./frontend
    restart: always
    depends_on:
      - verzeldb
    ports:
      - 80:3000
    
  adminer:
    image: wodby/adminer:4.8
    restart: always
    ports:
      - 8007:9000
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: verzeldb
      ADMINER_DEFAULT_DB_NAME: verzel
      ADMINER_DESIGN: pepa-linha
      PHP_POST_MAX_SIZE: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 2048M